### ISSUE TITLE
Unable to find dmd.conf on Mac when using Homebrew

### ISSUE THREAD

**Issue by SerialVelocity** [atilaneves/ac-dcd#12]
Hey,

Could you please add ```/usr/local/etc/dmd.conf``` to ```ac-dcd-find-imports-std``` so that dmd.conf can be found on Macs using the Homebrew package manager.

Thanks,
Nebster

**Comment by atilaneves** [comment]
I can't test if this would work or not since I don't have a mac. Since I can't test I can't tell if I've broken anything or even solved the problem. Please submit a pull request.
