### ISSUE TITLE
auto-completion don't work for dub packages out of box

### ISSUE THREAD

**Issue by Temzix** [atilaneves/ac-dcd#14]
Using GNU Emacs 24.4 on Windows.

Can't get autocompletion for vibe.d package even for "empty project", just "dub init" with vibe.d in AppData/Roaming/dub. Autocompletion for std works great! (after dcd.conf file in $HOME/dcd.conf).

**Comment by atilaneves** [comment]
I don't have ready access to a Windows box at the moment. What is the content of `flycheck-dmd-import-paths`? Is there anything in the messages buffer that could indicate what went wrong? Try setting `flycheck-dmd-import-paths` manually and see if it works then.

**Comment by Temzix** [comment]
I'm currently in ac-dcd.el in Emacs, there's no output in messages buffer.
I wrote to conf file manually all imports, when i evaluate function (ac-dcd-find-imports-std) i get these output (temp solution):
"-Ic:\\D\\dmd2\\src\\phobos\\" "-Ic:\\D\\dmd2\\src\\druntime\\import\\" "-Ic:\\Users\\Alex\\AppData\\Roaming\\dub\\packages\\vibe-d-0.7.23\\source\\" "-Ic:/Users/Alex/AppData/Roaming/dub/packages/libevent-2.0.1_2.0.16" "-Ic:/Users/Alex/AppData/Roaming/dub/packages/openssl-1.1.4_1.0.1g" "-Ic:/Users/Alex/AppData/Roaming/dub/packages/libev-5.0.0_4.04" "-Ic:/Users/Alex/AppData/Roaming/dub/packages/libasync-0.7.1/source/" "-Ic:/Users/Alex/AppData/Roaming/dub/packages/memutils-0.3.8/source/"

But i don't see any suggestions in "app.d" for example for "listenHTTP" when "vibe.d" imported.
Evaluation of (ac-dcd-find-imports-std) returns nil (but internally it gives those pathnames which i handwrote to conf file, but i can't change any code because i'm sure that it works for you, but don't work for me). Probably i'm missing something.

**Comment by Temzix** [comment]
So, basically in $HOME$ folder i've file dmd.conf with proper DFLAGS for phobos and druntime (this completion works) + as temporary solution i added vibe-d, libevent, openssl, libev, libasync, memutils pathes, so same function ac-dcd-find-imports-std returns all those pathes, but still it doesn't work for any dub package. Need help.

**Comment by Temzix** [comment]
You probably misspelled name of variable: flycheck-dmd-include-path, variable value is nil. (this variable should be set for completion and store pathes for all dub packages, right?)

**Comment by atilaneves** [comment]
The value being nil is why auto-completion isn't working. I don't know what's failing. I have to try this on Windows myself but I doubt it's just the OS. One never knows.

**Comment by Temzix** [comment]
Ok, I'll try to investigate myself. Probably my fault. I'll report results here when finish. Thanks!

**Comment by Temzix** [comment]
No problems with this repo, it just doesn't work for "vibe.d", issue opened in dcd itself, other completions working great! Sorry! (for vibe.vibe and etc.)
