### ISSUE TITLE
Could you create a new git tag for MELPA stable?

### ISSUE THREAD

**Issue by juanfra684** [atilaneves/ac-dcd#18]
Hi, I'm using the melpa stable packages for emacs. When I use the ac-dcd version available there (0.4 from 2014), ac-dcd-setup fails with the error `File mode specification error: (void-function ac-dcd-setup)`. Changing `ac-dcd.el` to the latest version from your repo, everything works fine. I'm using emacs 26.2.

Could you create a new git tag so melpa stable can update to it?.

**Comment by juanfra684** [comment]
Thanks for the fix. However, that's not enough. The previous version of the file contains `0.5` and the version on melpa stable is `0.4`. I guess that melpa only picks git tags for stable with the current recipe.

**Comment by atilaneves** [comment]
I think I forgot to push the tag. Done it now.
